
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'API AUTH CSV_FILE DELAY FILTER HEADER INTO JSON_FILE PROXY RETRIES SCRAPE SELECT URL USER_AGENT VALIDATE XML_FILEstatement : scrape_statement\n                | select_statement\n                | api_statementscrape_statement : SCRAPE URL INTO output_file optionsselect_statement : SCRAPE URL SELECT selector INTO output_file optionsapi_statement : SCRAPE URL API INTO output_file optionsoutput_file : JSON_FILE\n                  | CSV_FILE\n                  | XML_FILEselector : URLoptions : option options\n               | emptyoption : USER_AGENT\n             | DELAY\n             | RETRIES\n             | PROXY\n             | AUTH\n             | HEADER\n             | VALIDATE\n             | FILTERempty :'
    
_lr_action_items = {'SCRAPE':([0,],[5,]),'$end':([1,2,3,4,10,11,12,13,17,18,19,20,21,22,23,24,25,26,27,29,30,31,32,33,],[0,-1,-2,-3,-21,-7,-8,-9,-4,-21,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-11,-21,-6,-5,]),'URL':([5,8,],[6,14,]),'INTO':([6,9,14,15,],[7,16,-10,28,]),'SELECT':([6,],[8,]),'API':([6,],[9,]),'JSON_FILE':([7,16,28,],[11,11,11,]),'CSV_FILE':([7,16,28,],[12,12,12,]),'XML_FILE':([7,16,28,],[13,13,13,]),'USER_AGENT':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[20,-7,-8,-9,20,-13,-14,-15,-16,-17,-18,-19,-20,20,20,]),'DELAY':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[21,-7,-8,-9,21,-13,-14,-15,-16,-17,-18,-19,-20,21,21,]),'RETRIES':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[22,-7,-8,-9,22,-13,-14,-15,-16,-17,-18,-19,-20,22,22,]),'PROXY':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[23,-7,-8,-9,23,-13,-14,-15,-16,-17,-18,-19,-20,23,23,]),'AUTH':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[24,-7,-8,-9,24,-13,-14,-15,-16,-17,-18,-19,-20,24,24,]),'HEADER':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[25,-7,-8,-9,25,-13,-14,-15,-16,-17,-18,-19,-20,25,25,]),'VALIDATE':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[26,-7,-8,-9,26,-13,-14,-15,-16,-17,-18,-19,-20,26,26,]),'FILTER':([10,11,12,13,18,20,21,22,23,24,25,26,27,29,31,],[27,-7,-8,-9,27,-13,-14,-15,-16,-17,-18,-19,-20,27,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'scrape_statement':([0,],[2,]),'select_statement':([0,],[3,]),'api_statement':([0,],[4,]),'output_file':([7,16,28,],[10,29,31,]),'selector':([8,],[15,]),'options':([10,18,29,31,],[17,30,32,33,]),'option':([10,18,29,31,],[18,18,18,18,]),'empty':([10,18,29,31,],[19,19,19,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> scrape_statement','statement',1,'p_statement','parser.py',8),
  ('statement -> select_statement','statement',1,'p_statement','parser.py',9),
  ('statement -> api_statement','statement',1,'p_statement','parser.py',10),
  ('scrape_statement -> SCRAPE URL INTO output_file options','scrape_statement',5,'p_scrape_statement','parser.py',14),
  ('select_statement -> SCRAPE URL SELECT selector INTO output_file options','select_statement',7,'p_select_statement','parser.py',24),
  ('api_statement -> SCRAPE URL API INTO output_file options','api_statement',6,'p_api_statement','parser.py',35),
  ('output_file -> JSON_FILE','output_file',1,'p_output_file','parser.py',45),
  ('output_file -> CSV_FILE','output_file',1,'p_output_file','parser.py',46),
  ('output_file -> XML_FILE','output_file',1,'p_output_file','parser.py',47),
  ('selector -> URL','selector',1,'p_selector','parser.py',51),
  ('options -> option options','options',2,'p_options','parser.py',55),
  ('options -> empty','options',1,'p_options','parser.py',56),
  ('option -> USER_AGENT','option',1,'p_option','parser.py',66),
  ('option -> DELAY','option',1,'p_option','parser.py',67),
  ('option -> RETRIES','option',1,'p_option','parser.py',68),
  ('option -> PROXY','option',1,'p_option','parser.py',69),
  ('option -> AUTH','option',1,'p_option','parser.py',70),
  ('option -> HEADER','option',1,'p_option','parser.py',71),
  ('option -> VALIDATE','option',1,'p_option','parser.py',72),
  ('option -> FILTER','option',1,'p_option','parser.py',73),
  ('empty -> <empty>','empty',0,'p_empty','parser.py',77),
]
